// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6d8wWLX-YuUHnkGKwerL7DhhsopHej-4',
    appId: '1:185609375617:web:6b97255ea4560b42bee280',
    messagingSenderId: '185609375617',
    projectId: 'threet-multiplayer',
    authDomain: 'threet-multiplayer.firebaseapp.com',
    storageBucket: 'threet-multiplayer.firebasestorage.app',
    measurementId: 'G-Q9BEG3MB84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAls2QeKicdhyNsZmUiOO80nSSnAEFDHjs',
    appId: '1:185609375617:android:82a6676a37195fcebee280',
    messagingSenderId: '185609375617',
    projectId: 'threet-multiplayer',
    storageBucket: 'threet-multiplayer.firebasestorage.app',
  );
}
